### ISSUE TITLE
Domain Buying

### ISSUE THREAD

**Issue by kustnodi** [bowtie-io/springboard#3]
Was getting a false negative when trying to acquire the growconnect.net domain through bowtie.  growconnect.net was available

![image](https://cloud.githubusercontent.com/assets/3536024/5989836/669c8b12-a952-11e4-83e7-cb0fe0f2e174.png)

**Comment by jkassemi** [comment]
Sorry for missing this one, @kustnodi, we shipped the fix for this problem a little earlier. You should be able to try again successfully.
