### ISSUE TITLE
Trying to use custom domain with bowtie

### ISSUE THREAD

**Issue by kustnodi** [bowtie-io/springboard#4]
We have the growconnect.biz domain and I am attempting to point that at growconnect.bowtied.io

When you hit growconnect.biz it eventually ends up at bowtie.io which I didn't expect

![image](https://cloud.githubusercontent.com/assets/3536024/5990112/41e220e0-a95f-11e4-9eac-20e1025af3a8.png)

**Comment by jkassemi** [comment]
Thanks for the report ,@kustnodi! We've addressed a configuration issue that caused the problem.

Can you contact me at james@seedworthy.com to arrange getting your existing cert installed for that domain?

-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v2

mQINBFRL/sABEACiG2Bq+GPE5WlfPkHLDvrIRNxlmB6wGEnhchwfvPE63Z5cOlaa
jLs9VqQ6wptIuUpRe9mq7RqBSN5oWBhymo2vZaYM4PfbzZRsBJlbBzjcACQ8BNG1
xSbb1+Ba/Cx449hFxar4khFQBsR2yfB2dTn2YXXirXORPvvReUA0rA3gozCRrh56
ui/u4Y3Qi9NhzsHTxzKvg4cJAjAh30NFO/1urx35d8Pacs3dYZFLvEQ6+hdSFY3X
TbIvHyJ/WiB3BkGCge5hCankyuqPZibzH3907pPvc1+Q/dWY670r8ADIKnXNgGOC
ybO56IZsv+I61bAZJboPOnTAn2/Elv5kpet4+1WaXOfLPEaqAwz/f7dqkwhnvI5a
unQuv185IODOR46JxC1beZO8jAWgzKqDvlmzORiTMARwWxehW38scuM+cmeCRzp6
VYh9OrO1HUmt24hQCcu5OeGBh9MxFkOhr+arHhaIz3+7c04AMcNxdAhRFhM67Brm
aYNkP96CrQonhCQSKwnHRdDXzVsvrAycIGPyTQvxq6JeHtfgTrPwENLGzeILekJA
EOcP3YxKrAT8Cy9+J/sRcnmzk1d6KdKagJaI9NKGdBLlRZqHWi5//adAT4SX8dkq
r7L4LU8oWgHknYs4UPLULeiSJU2SO57Jqa+mITgif7tdXTg2sJUQWBKDHwARAQAB
tCJKYW1lcyBLYXNzZW1pIDxqa2Fzc2VtaUBnbWFpbC5jb20+iQI/BBMBAgApBQJU
S/7AAhsDBQkB4TOABwsJCAcDAgEGFQgCCQoLBBYCAwECHgECF4AACgkQRdluY5nD
HPD5ohAAh5ah2FXum9IBTnYYcXIxKhnplBrsz7ZJNLPbYsv6w02rNV8M64tjJTag
H7IKbk3B+f0KXgFweCyE8EV6qHzVYYMR5AHdbNGEV/Sys3fgBsTgJ9PrWr9Ry2HV
H5jVgVs1YiQniDBuptVUYPLzIQsgEkb3LSILtd8WWxiGH7MKumQgDQ5G4BBdLS3+
yZclaBehegGQZj55Ovm1BDCWZLlnlDEELxWqv9Z/1JQVZt1zXERMcXc53si5Iy3Q
Vy5kPw68fhdc2h+rIBgI9+pOgjuiuCpBUjLMSe/IOAqBTOC4RiXj2KtZNWSfVPJi
hSrcWmPsIqsgpJIAe6JUJ/kKgnPq+KOVQLM3jTRFrDmASU5dC3YAAOTVk/W2lw7Q
C0W0Tgu/wMdoWlc17DcsU2DXL7jj2ST15N7yYD6F/xrHfhhcpzWR9BhMGweJ52a5
Rr8kam1We2DZUWMkRXeYwyN9aI2A560tEH11E2gVUmRc3uyzP4yEVBbIyz53dcH7
gI72/D2iLECKZOmnKl2ZNKd8BZDCNDpmW1ot+/7jTzAVQhdUjqRw9PXEplMuQkHp
3YKwFlokUaRvA8QgqEXrk9qXl4TcL2or9EoWA2yNccI4v5PBw8B27MJdB93xEvpJ
0ilD3BYo0O6iL52gzjdZEykwMwz35kN4S3i4OcDTqVvzKxX4KbC5Ag0EVEv+wAEQ
ANCd4bryNKJQANjCpqxzuZ6q6dCR7MWJ5NbpsSI2gwnR2V8sK6QRK6AVmSeVSaBd
i03tMLuyV+hbDAEE9EhAMW2hFDbXpVsJPJxTymtrbL0uytXUEZ+MAy538u51MYo6
9QH2s+dHonUE3aIj2E69gFvjmlsA4Nbd2rEH5A5p3ONMGe2BflctH3oFwMCT3785
W46I/ITKk0yJREb7UJhJTmC+Ps4HpkImP/SiJj0LWFDp8+jeLFh5nQEKWKaOOJAN
x6G64y+IhMiRhMLVDbbHrcvasp3GY4IPq46lxjcxw/Eu99XjBs327zjqxpTwAU6z
M34JSemFluzQ6wTr8uqKUuWdD5Xu7wO/J+TC6ZCJNILfF5xMSCDFrM5tLZ+oUvv+
SzNc0ZDFonuKE68cZrj4f/7E6bAgto5kgiEL5a0EiWAMYGNIwOGNVEYblSl0KUHd
aNo7zJlFiDN3iIOEXH2q6Wd+wcZwPkPj723mTYw8/5Vj1RWUlENWXHQMNw89zRAL
iFuIIi/vPnoZUkm81mb1zZ2la8M0mL/h3ENHiTOfgABRlxdqHz8k+77nopaw8ilb
rxcdNFqQfPQMyDodnlMhxXQFWJH3bKpnqpLO3S++mZb4TgVDywGai14LO8z5JHqN
cGeQNcEDzI5EW1OPKTsZ75xLaRHa2Xz44yYQiR6cJg19ABEBAAGJAiUEGAECAA8F
AlRL/sACGwwFCQHhM4AACgkQRdluY5nDHPDu/w/+ME/+djWzaAFdOO9XwIjyvvCT
zs+FgBwuzp6X7ZA1OddzgTJfutq8C9WbYgUNSShTfHtiP6UWRT7PC8d+pulZ5VI4
zeeH6oNMrEbyqF4Rjih1OutPhv/hlEMNmJo8rb2JuSWNaIa/KAfKsewY4DADJ1lJ
UXUsITa9Lo//QBHqGAvTFzx7PdjUD2Au8ynrNuLwGM2ZYbzZNyCkBG1tOxJxxosZ
hM2zVC2zqlsDJxgZYgRfK31Chm09VZv6RBInM7y9T2xdnO33046P/PQDshVTLiYb
m2KAfMWefHilOuoT5I2QNbXK6s8AX5qOdQbIvA/nvIyuPIrPwbGubDgSlwMY7G0K
tGwa1q9a4W/m88745EbpvAgOyMruq2GuLqojN/FVKnj8Lm6R0oGZxorgaQDk1/6u
3qwVxZqhIUUvKl1GWA4zzXS9Wb6/0xb2cngvIYm6GwKrqoBrCroNp907fPbUuQAQ
b6IQC8jzznR/DHyJZR3WRt31NTwxDQa2ZGZ6/FFNdxbGGVHVVn4u+B18azag5C9Q
iO6Xf7LDVUBBTSSoLs2mutvYWea2JdidWiVViy2j0JnP6kQ5mz8wak/b5jpb88BS
D6Gow01+XhiGNPCCp4Morz6cfmTliwt5oRx1IHe1heBURKFQsW2sgfZj5a0QuRyS
Nov96nOV+Hz9TsCVQyw=
=ofZt
-----END PGP PUBLIC KEY BLOCK-----

**Comment by jkassemi** [comment]
Additionally, we've made some UI changes to make this process simpler.

Documentation for configuring existing domains (not purchased with BowTie) with external DNS is provided at https://bowtie.io/docs/#getting-started-live-applications-dns-settings-for-existing-domains.

We're not currently officially supporting BowTie-hosted DNS with existing domains.
