### ISSUE TITLE
Hooking up backend

### ISSUE THREAD

**Issue by kustnodi** [bowtie-io/springboard#5]
Do you have any documentation on hooking up the backend?  I have some webservices up and inserted the url in the backend configuration and now don't know what to do.  I expected it to just proxy calls to the other server but it doesn't seem to, I get 404s.  I tried the following
growconnect.bowtied.io/myremoteservice/
growconnect.bowtied.io/api/myremoteservice/
growconnect.bowtied.io/backend/myremoteservice/

**Comment by jkassemi** [comment]
I may be late to the party and this changed before I got here, but I'm not seeing a backend url configured for growconnect.bowtied.io.

You're absolutely right about the proxying. The only requests handled before they'll be sent to your backend will be `/users.*` and `/bowtie/.*`.

**Comment by kustnodi** [comment]
Well isn't that awesome.  Put the url in and it works fine X(.  Thanks
